name: Release

on:
  push: 
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola Andy!"
      - name: Dime la fecha
        run: date